### ISSUE TITLE
"Performance?"?

### ISSUE THREAD

**Issue by fbiville** [igorw/naegleria#2]
What does [he](https://github.com/igorw/naegleria/issues/1) mean with "What do you mean with: `It's assembly, so probably faster than C`."?
Thanks :)

**Comment by igorw** [comment]
no fucking clue

**Comment by rdebath** [comment]
Probably means that just being in assembly isn't enough.
Interestingly though, it's current speed is even lower than I would expect, for some reason it's almost exactly the same speed as a trivial C conversion; like below and slower than some smallish C interpreters like [https://gist.github.com/rdebath/a12653a3c167cf93ab6a](https://gist.github.com/rdebath/a12653a3c167cf93ab6a) that puts it a long was behind the fastest ones (so far!).

``` C
#include <stdio.h>
#include <string.h>

char * bf = "+-><[].,";
char * cc[] = {
        "array[p]++;",
        "array[p]--;",
        "p++;",
        "p--;",
        "while(array[p]) {",
        "}",
        "putchar(array[p]);",
        "array[p]=getchar();"
};

int main(int argc, char ** argv) {
        char * s;
        int c;

        puts(   "#include <stdio.h>"
        "\n"    "int array[30000];"
        "\n"    "int main(void){"
        "\n"    "register int p = 0;"
        "\n"    "setbuf(stdout,0);");

        while((c=getchar()) != EOF)
                if ((s = strchr(bf, c)))
                        puts(cc[s-bf]);

        puts("return 0;}");
        return 0;
}
```
